import type { Metadata } from 'next'
import './globals.css'
import { Quicksand } from 'next/font/google'
import Theme from './_ui/theme'
import { cookies } from 'next/headers'

const quicksand = Quicksand({
  subsets: ['latin', 'vietnamese']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const cookieThemeValue = cookies().get('theme')?.value
  const darkMode = typeof cookieThemeValue === 'string' && cookieThemeValue === 'dark'

  return (
    <html lang="en" className={`${darkMode && 'dark'}`}>
      <body className={`${quicksand.className} bg-purple-100 dark:bg-neutral-950/75`}>
        <div className='min-h-screen flex items-center justify-center'>
          <Theme mode={Boolean(darkMode)} />
          {children}
        </div>
      </body>
    </html>
  )
}
